version: '3.9'

services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    environment: 
      - PUID=1000
      - GUID=1000
      - MEM_LIMIT=1024M
      - MEM_STARTUP=1024M
    volumes:
      - ../../data/unifi-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
