version: '3.9'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - ../../data/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../../data/mqtt/data:/mosquitto/data
      - ../../data/mqtt/log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      - mqtt
    restart: unless-stopped

networks:
  mqtt:
    external: true
