version: '3.9'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    environment: 
      - TZ=Europe/Amsterdam
    volumes:
      - ../../data/zigbee2mqtt:/app/data
    devices:
      - /dev/usb_zigbee:/dev/usb_zigbee
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.zigbee2mqtt.rule=Host(`${DASHBOARD_URL}`)
      - traefik.http.routers.zigbee2mqtt.entrypoints=https
      - traefik.http.routers.zigbee2mqtt.tls=true
      - traefik.http.routers.zigbee2mqtt.tls.certresolver=letsencrypt
      - traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080
    networks:
      - traefik
      - mqtt
    restart: unless-stopped

networks:
  traefik:
    external: true
  mqtt:
    external: true
